version: "3.9"
services:
  web:
    container_name: web
    build:
      context: ../a11ywatch-web
      dockerfile: Dockerfile.dev
    volumes:
      - ../a11ywatch-web/src:/app/src
      - ../a11ywatch-web/next.config.js:/app/next.config.js
      - ../a11ywatch-web/tailwind.config.js:/app/tailwind.config.js
      - ../a11ywatch-web/public:/app/public
    ports:
      - "3000:3000"
    environment:
      - API=${API:-http://localhost:3280/graphql}
      - WEB_SOCKET_URL=${WEB_SOCKET_URL:-ws://localhost:3280/graphql}
      - NODE_ENV=${NODE_ENV:-development}
      - STRIPE_KEY=${STRIPE_KEY_WEB}
      - INTERCOM_APPID=${INTERCOM_APPID}
      - INTERCOM_ENABLED=${INTERCOM_ENABLED}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    networks:
      - front-net

  api:
    container_name: api
    build:
      context: ../a11ywatch-core
      dockerfile: Dockerfile.dev
    volumes:
      - ../a11ywatch-core/src:/usr/src/app/src
    ports:
      - 3280:8080
      - 50051
    depends_on:
      - mongodb
    environment:
      - DB_URL=${DB_URL:-mongodb://mongodb:27017/?compressors=zlib&gssapiServiceName=mongodb}
      - DB_NAME=${DB_NAME:-a11ywatch}
      - APOLLO_GRAPH_VARIANT=${APOLLO_GRAPH_VARIANT:-current}
      - APOLLO_SCHEMA_REPORTING=${APOLLO_SCHEMA_REPORTING:-false}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
      - GRAPHQL_PORT=${GRAPHQL_PORT:-8080}
      - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
      - EMAIL_CLIENT_ID=${EMAIL_CLIENT_ID}
      - EMAIL_CLIENT_KEY=${EMAIL_CLIENT_KEY}
      - STRIPE_KEY=${STRIPE_KEY}
      - SCRIPTS_CDN_URL=${SCRIPTS_CDN_URL:-http://localhost:8090/api}
      - ROOT_URL=${ROOT_URL:-http://localhost:8080}
      - STRIPE_BASIC_PLAN=${STRIPE_BASIC_PLAN}
      - STRIPE_PREMIUM_PLAN=${STRIPE_PREMIUM_PLAN}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - ADMIN_ORIGIN=${ADMIN_ORIGIN}
      - DOCKER_ENV=true
      - SUPER_MODE=${SUPER_MODE}
      - REDIS_CLIENT=${REDIS_CLIENT:-redis://redis:6379}
      - REDIS_HOST=redis
    networks:
      - back-net
      - front-net

  pagemind:
    container_name: pagemind
    build:
      context: ../pagemind
      dockerfile: Dockerfile.dev
    volumes:
      - ../pagemind/src:/usr/src/app/src
    ports:
      - "8040"
      - 50052
    environment:
      - SCRIPTS_CDN_URL=${SCRIPTS_CDN_URL:-http://cdn-server:8090/api}
      - SCRIPTS_CDN_URL_HOST=${SCRIPTS_CDN_URL_HOST:-http://localhost:8090/cdn}
      - PORT=${PAGEMIND_PORT:-8040}
      - ASSETS_CDN=${ASSETS_CDN:-http://localhost:8090}
      - DOCKER=true
    networks:
      - back-net

  mav:
    container_name: mav
    build:
      context: ../mav
      dockerfile: Dockerfile.dev
    volumes:
      - ../mav/src:/usr/src/app/src
    ports:
      - 8020
      - 50053
    environment:
      - PORT=${MAV_PORT:-8020}
      - DOCKER_ENV=true
    networks:
      - back-net

  cdn-server:
    container_name: cdn-server
    build:
      context: ../elastic-cdn
      dockerfile: Dockerfile.dev
    volumes:
      - ../elastic-cdn/src:/usr/src/app/src
    ports:
      - "8090:8090"
      - 50054
    environment:
      - PORT=${ELASTIC_CDN_PORT:-8090}
    networks:
      - back-net

  crawler:
    container_name: crawler
    build:
      context: ../crawler
      dockerfile: Dockerfile.dev
    volumes:
      - ../crawler/src:/usr/src/app/src
    ports:
      - 50055
    networks:
      - back-net

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-a11ywatch}
    networks:
      - back-net

  mongoclient:
    container_name: mongoclient
    image: mongo-express
    ports:
      - "3100:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=${HOST:-mongodb://mongodb:27017/?compressors=zlib&gssapiServiceName=mongodb}
    depends_on:
      - mongodb
    networks:
      - back-net

  redis:
    container_name: redis
    image: redis:7.0-rc2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - back-net

  chrome:
    container_name: chrome
    image: a11ywatch/chrome
    command:
      [
        chromium-browser,
        "--headless",
        "--no-sandbox",
        "--hide-scrollbars",
        "--mute-audio",
        "--no-zygote",
        "--no-first-run",
        "--remote-debugging-address=0.0.0.0",
        "--remote-debugging-port=9222",
        "--max-wait-for-load=2500",
        "--allow-running-insecure-content",
        "--autoplay-policy=user-gesture-required",
        "--disable-default-apps",
        "--disable-storage-reset",
        "--disable-dev-shm-usage",
        "--disable-http2",
        "--disable-domain-reliability",
        "--disable-component-update",
        "--disable-sync",
        "--disable-background-networking",
        "--disable-background-timer-throttling",
        "--disable-notifications",
        "--disable-accelerated-2d-canvas",
        "--disable-accelerated-video-decode",
        "--disable-extensions",
        "--disable-popup-blocking",
        "--disable-renderer-backgrounding",
        "--disable-client-side-phishing-detection",
        "--disable-setuid-sandbox",
        "--disable-hang-monitor",
        "--disable-features=ScriptStreaming,TranslateUI,BlinkGenPropertyTrees",
      ]
    ports:
      - "9222:9222"
    networks:
      - back-net

volumes:
  mongodb:

networks:
  front-net:
  back-net:
