version: "3.0"
services:
  api:
    container_name: api
    env_file: ./api/.env
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/.env:/usr/src/app/.env
      - ./api/package.json:/usr/src/app/package.json
      - ./api/package-lock.json:/usr/src/app/package-lock.json
      - ./api/__tests__:/usr/src/app/__tests__
      - /usr/src/app/node_modules
    networks:
      - back-net
      - front-net
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  pagemind:
    container_name: pagemind
    image: jeffmendez19/pagemind
    networks:
      - back-net
    ports:
      - "8040:8040"
    environment:
      - SCRIPTS_CDN_URL=${SCRIPTS_CDN_URL:-http://cdn-server:8090/api}
      - SCRIPTS_CDN_URL_HOST=${SCRIPTS_CDN_URL_HOST:-http://localhost:8090/cdn}
      - AI_SERVICE_URL=${SCRIPTS_CDN_URL:-http://mav:8020}
      - PORT=${PAGEMIND_PORT:-8040}
      - LOGGER_ENABLED=${LOGGER_ENABLED:-true}

  mav:
    container_name: mav
    image: jeffmendez19/mav
    networks:
      - back-net
    ports:
      - "8020:8020"
    environment:
      - MAIN_API_URL=${MAIN_API_URL:-http://api:8080}
      - LOGGER_ENABLED=${LOGGER_ENABLED:-true}
      - PORT=${MAV_PORT:-8020}
      - DOCKER_ENV=true

  logger:
    container_name: logger
    image: jeffmendez19/logger
    volumes:
      - /usr/src/app/dist/logs
    networks:
      - back-net
    ports:
      - "8022:8022"
    environment:
      - PORT=${LOGGER_PORT:-8022}
  
  cdn-server:
    container_name: cdn-server
    image: jeffmendez19/elastic-cdn
    networks:
      - back-net
      - front-net
    ports:
      - "8090:8090"
    environment:
      - PORT=${ELASTIC_CDN_PORT:-8090}
      - LOGGER_ENABLED=${LOGGER_ENABLED:-true}

  iframe-server:
    container_name: iframe-server
    image: jeffmendez19/iframer
    networks:
      - front-net
    ports:
      - "8010:8010"
    environment:
      - PORT=${IFRAMER_PORT:-8010}
      - LOGGER_ENABLED=${LOGGER_ENABLED:-true}

  crawler:
    container_name: crawler
    image: jeffmendez19/crawler
    networks:
      - back-net
    ports:
      - "8000:8000"
    environment: 
      - CRAWL_URL=http://api:8080/api/website-crawl-background

  mongodb:
    container_name: mongodb
    networks:
      - back-net
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-a11ywatch}

  mongoclient:
    container_name: mongoclient
    networks:
      - back-net
    image: huggingface/mongoku
    ports:
      - "3100:3100"
    environment:
      - MONGOKU_DEFAULT_HOST=${HOST:-mongodb://mongodb:27017/?compressors=zlib&gssapiServiceName=mongodb}
    depends_on:
      - mongodb

networks:
  front-net:
  back-net:
volumes:
  mongodb:
  api:
  watcher:
  logger:
