version: "3.0"
services:
  api:
    container_name: api
    env_file: ./api/.env
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/__tests__:/usr/src/app/__tests__
      - /usr/src/app/node_modules
    networks:
      - back-net
      - front-net
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  angelica:
    container_name: angelica
    env_file: ./angelica/.env
    build:
      context: ./angelica
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./angelica/src:/usr/src/app/src
      - ./angelica/__tests__:/usr/src/app/__tests__
      - /usr/src/app/node_modules
    networks:
      - back-net
    ports:
      - "8040:8040"

  mav:
    container_name: mav
    env_file: ./mav/.env
    build:
      context: ./mav
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./mav/src:/usr/src/app/src
      - ./mav/__tests__:/usr/src/app/__tests__
      - /usr/src/app/node_modules
    networks:
      - back-net
    ports:
      - "8020:8020"

  logger:
    container_name: logger
    env_file: ./logger/.env
    build:
      context: ./logger
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./logger/src:/usr/src/app/src
      - ./logger/__tests__:/usr/src/app/__tests__
      - /usr/src/app/node_modules
    networks:
      - back-net
    ports:
      - "8022:8022"

  cdn-server:
    env_file: ./cdn-server/.env
    container_name: cdn-server
    build:
      context: ./cdn-server
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./cdn-server/src:/usr/src/app/src
      - ./cdn-server/__tests__:/usr/src/app/__tests__
      - /usr/src/app/node_modules
    networks:
      - back-net
      - front-net
    ports:
      - "8090:8090"

  iframe-server:
    env_file: ./iframe-server/.env
    container_name: iframe-server
    build:
      context: ./iframe-server
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./iframe-server/src:/usr/src/app/src
      - ./iframe-server/__tests__:/usr/src/app/__tests__
      - /usr/src/app/node_modules
    networks:
      - front-net
    ports:
      - "8010:8010"

  watcher:
    container_name: watcher
    env_file: ./watcher/.env
    build:
      context: ./watcher
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./watcher/src:/usr/src/app/src
      - ./watcher/scripts:/usr/src/app/scripts
      - ./watcher/tests:/usr/src/app/tests
      - ./watcher/.env:/usr/src/app/.env
    networks:
      - back-net
    ports:
      - "8000:8000"

  mongodb:
    container_name: mongodb
    networks:
      - back-net
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-a11ywatch}

networks:
  front-net:
  back-net:
volumes:
  mongodb:
  api:
  angelica:
  watcher:
  cdn-server:
  iframe-server:
  logger:
