version: 2.1
jobs:
  cli:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "./cli/Cargo.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install Docker Compose and Rust
          environment:
            COMPOSE_VERSION: "1.29.2"
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          description: "Install the A11yWatch CLI"
          command: cargo install --path ./cli
      - run:
          description: "Start the backend instance"
          command: a11ywatch start
      - run:
          description: "Start the frontend instance"
          command: a11ywatch start -f
      - run:
          description: "Run a website basic scan"
          command: a11ywatch scan --url ${WEBSITE_SCAN_URL}
      - save_cache:
          paths:
            - ~/usr/local/lib/target
          key: node-v1-{{ .Branch }}-{{ checksum "./cli/Cargo.lock" }}
workflows:
  build_and_test:
    jobs:
      - cli
