version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  api:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "api/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: cd api && npm ci && bash ./bootstrap.sh && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "api/package-lock.json" }}
      - codecov/upload:
          file: "./api/coverage/clover.xml"
          conf: "./codecov.yml"

workflows:
  build_and_test:
    jobs:
      - api
