[package]
name = "a11ywatch_cli"
version = "0.0.14"
authors = ["j-mendez <jeff@a11ywatch.com>"]
description = "A11yWatch CLI to build, deploy, and manage all things."
repository = "https://github.com/a11ywatch/a11ywatch"
readme = "README.md"
keywords = ["a11ywatch", "accessibility", "website_improvement"]
categories = ["accessibility", "command-line-utilities", "development-tools::build-utils"]
license = "MIT"
documentation = "https://docs.rs/a11ywatch_cli"
include = ["src/*", "LICENSE", "README.md"]
edition = "2021"

[dependencies]
clap = { version = "3.1.5", features = ["derive"] }

[[bin]]
name = "a11ywatch"
path = "src/main.rs"

